name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
prerelease: true
prerelease-identifier: b
categories:
  - title: '💥 Breaking Changes' 
    labels:
      - 'breaking'
  - title: '✨ New Features'
    labels:
      - 'new-feature'
  - title: '👍 Improved Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧪 Testing'
    label: 'test'
  - title: '⚒️ Continous Integration'
    label: 'ci'
  - title: '🐧 Hosting and Docker'
    label: 'hosting'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/^docs?/.+/'
  - label: 'bug'
    branch:
      - '/^fix\/.+/'
    title:
      - '/\bfix\b/i'
  - label: 'enhancement'
    branch:
      - '/^feature\/.+/'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'new-feature'
      - 'feature'
      - 'enhancement'
      - 'chore'
      - 'documentation'
      - 'dependencies'
      - 'test'
      - 'hosting'
      - 'ci'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/olibos/ha-addon-curve/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION